export const FETCH_DEPARTURES       = 'FETCH_DEPARTURES';
export const RELOAD_DEPARTURES      = 'RELOAD_DEPARTURES';
export const RECEIVE_DEPARTURES     = 'RECEIVE_DEPARTURES';
export const ERROR_FETCH_DEPARTURES = 'ERROR_FETCH_DEPARTURES';

export const FETCH_SERVICE          = 'FETCH_SERVICE';
export const RELOAD_SERVICE         = 'RELOAD_SERVICE';
export const RECEIVE_SERVICE        = 'RECEIVE_SERVICE';
export const ERROR_FETCH_SERVICE    = 'ERROR_FETCH_SERVICE';

export const FETCH_STATIONS         = 'FETCH_STATIONS';
export const SELECT_STATION         = 'SELECT_STATION';
export const RECEIVE_STATIONS       = 'RECEIVE_STATIONS';
export const ERROR_FETCH_STATIONS   = 'ERROR_FETCH_STATIONS';